interpreter:
    type: electra
    path: 
    use_logits: False
paths:
    data_dir: spouse
    exp_dir: explanations
    save_dir: spouse/new_features/spouse-electra-exp-adam
data_reader: babble_reader
