interpreter:
    type: bert
    path: bert/pytorch_model.bin
    use_logits: False
paths:
    data_dir: spouse
    exp_dir: base-explanations
    save_dir: spouse/new_features/new-noexp-features_adam
data_reader: babble_reader
