interpreter:
    type: electra
    path: 
    use_logits: False
paths:
    data_dir: spouse
    exp_dir: random_explanations_v1
    save_dir: spouse/new_features/spouse-electra-random
data_reader: babble_reader