interpreter:
    type: electra
    path: 
    use_logits: False
paths:
    data_dir: spouse
    exp_dir: base-explanations
    save_dir: spouse/new_features/new-electra-mnli-noexp-features
data_reader: babble_reader
