interpreter:
    type: 'bert'
    path: '/u/scr/smurty/bert_base_mnli/best_model' 
    use_logits: False
paths:
    data_dir: '/u/scr/smurty/spouse_data_cr'
    exp_dir: 'explanations'
    save_dir: '/u/scr/smurty/spouse_data_cr/expbert-features'
data_reader: 'babble_reader'
